FROM python:3.11-slim

WORKDIR /app

# Copy only requirements first to leverage Docker cache
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the project (including the notebook)
COPY . .

# Command to execute the notebook using papermill when the container starts
# It reads /app/nb.ipynb and writes the executed output (with results) to /app/nb_output.ipynb
# It will use the MLFLOW_TRACKING_URI environment variable set in docker-compose.yml
CMD ["papermill", "nb.ipynb", "nb_output.ipynb"]